### ISSUE TITLE
 couldn't see text entered in address field and search field

### ISSUE THREAD

**Issue by erdosnew** [conformal/xombrero#126] opened 2016-01-22 03:15 UTC
i installed xombrero in debian8.  however, when i entered a web address or a search word in the browser. i couldn't see it.  not sure where to change the setting to make the text being entered visible.

**Comment by lhark** [comment] 2016-01-22 12:35
I encountered the same problem on my computer running GTK3. It seems to be related with debian default gtk3 theme. Everything working perfectly with gtk2 though.

**Comment by mvhulten** [comment] 2016-02-07 09:40
I experienced the same problem on Debian 8.

Duplicate of #97, which has probably a more useful description.

**Comment by marcopeereboom** [comment] 2016-03-21 23:36
I have since created a workaround on bitrig/openbsd.  gtk3 does bad things so just use gtk2.  Bonus, it’s faster too.  gtk3 buys us nothing.

**Comment by marcopeereboom** [comment] 2016-05-03 18:18
This should be fixed in latest current.

**Closed by marcopeereboom** 2016-05-03 18:18 UTC
