### ISSUE TITLE
Socket breaks with restart

### ISSUE THREAD

**Issue by Link-Satonaka** [conformal/xombrero#42] opened 2014-03-11 20:53 UTC
Title says it all- the socket does not properly work with with the built in restart command.

**Comment by marcopeereboom** [comment] 2015-02-17 17:32
The socket code does and always has done all the magic to kill the socket file and refresh it on restart/crashes etc.  So I need specific steps on how to recreate this.  I am closing this until I receive that information since I can not reproduce it on my OS.

**Closed by marcopeereboom** 2015-02-17 17:32 UTC
